### ISSUE TITLE
Pagination bug

### ISSUE THREAD

**Issue by mr-manuel** [Froxlor/Froxlor#1062] opened 2023-01-08 16:58 UTC
**Describe the bug**
The pagination is always enabled, even if there are only 2 rows. In addition you can go forward to infinity.

![grafik](https://user-images.githubusercontent.com/12592765/211208748-51b7c453-3fa7-4d99-aea5-8b8d9d87494d.png)

**System information**
* Froxlor version: 2.0.1

**To Reproduce**
1. Go to any page with pagination
2. Click on the next button how often you like

**Expected behavior**
Pagination should only be enabled when needed. Also it should not be possible to go forwand infinitely.

**Comment by d00p** [comment] 2023-01-08 17:03
Cannot reproduce, also not in demo

**Comment by mr-manuel** [comment] 2023-01-08 17:07
Should I send you logs or give you access to the instance?

**Comment by d00p** [comment] 2023-01-08 17:09
That would be helpful. Best via DM on Discord

**Comment by d00p** [comment] 2023-01-08 18:04
fixed in https://github.com/Froxlor/Froxlor/commit/fb7d65d645efabe74e8ae9981866b2057f0000ea

**Closed by d00p** 2023-01-08 18:04 UTC
