### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LogoJK** [Froxlor/Froxlor#977] opened 2021-09-22 11:10 UTC
Idk if this is alwready a thing but i would like that customers can create Domains by them selv.

You can der a Nummer of Domains a customer can have when creating bis Account (Also an unlimited option)

Best regards

**Comment by d00p** [comment] 2021-09-22 11:16
There are a lot of settings to be set for a main-domain which should not be of any customers concern (and the wrong changes may lead to the webserver not working for all customers).

**Comment by LogoJK** [comment] 2021-09-22 13:05
Well male customer only edit the Main things and the other things only for admins

**Comment by d00p** [comment] 2022-03-04 08:22
duplicate of #729

**Closed by d00p** 2022-03-04 08:22 UTC
