### ISSUE TITLE
[bug] init.d commands on CentOS 7

### ISSUE THREAD

**Issue by k5sql** [Froxlor/Froxlor#772] opened 2019-12-07 07:31 UTC
# Bug report 

# Summary
* It seems that the defaults expect/assume '/etc/init.d/<servicename>' commands to restart/reload services. CentOS 7 uses SystemD and nearly every service now requires 'systemctl'. 

* Positive note: replacing all the hard-coded defaults with the proper systemctl command in the editable (thanks for that!) fields in the appropriate settings menu works just fine.

# System information
* Froxlor version: 0.10.8
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: CentOS Linux release 7.7.1908 (Core)

# Steps to reproduce

1. Install froxlor on CentOS 7

# Expected behavior

1. Choice of OS (or auto detection)
2. Inclusion of correct commands (systemctl) as a result of said choice/detection

# Actual behavior

1. Many services default to '/etc/init.d/servicename' instead of systemctl

# Workaround
1. Replacing offending /etc/init.d entries with 'systemctl reload-or-restart servicename' in the appropriate edit fields in Settings resolves the failure to reload services.

# Comment
* I have intentionally not updated to 0.10.9 as the system was installed just 2 days ago and is in the process of going live. Due to bug reports, I am waiting until I am sure the update will not negatively impact production

**Comment by d00p** [comment] 2019-12-07 07:43
Workaround: eh, that's the whole point for these values to be settings. There's nothing hardcoded.

Comment: you do know that 0.10.9 fixes bugs from previous versions? Just read the announcement

**Comment by k5sql** [comment] 2019-12-07 07:56
Apologies if I described that incorrectly @d00p - Just meant that the 'defaults' that got put in upon setting up the panel were all /etc/init.d flavor -- unless I missed something, there wasn't an option to select. But as with the other Cent-specific item I reported, glad that the options are editable at all. A very welcome design choice.

**Comment by d00p** [comment] 2019-12-07 08:05
So this is kind of a duplicate of #771 then?

**Comment by k5sql** [comment] 2019-12-07 08:09
I suppose it could be - was not entirely sure if I should roll it all into one GH issue or separate them. What I do for my day job demands unique items, even if similar, to be filed separately. Guess it's just a habit by now :)

**Comment by d00p** [comment] 2019-12-08 08:38
Duplicate of #771

**Closed by d00p** 2019-12-08 08:38 UTC
Labels: duplicate
