### ISSUE TITLE
Error in SQL File

### ISSUE THREAD

**Issue by SurtursRevenge** [Froxlor/Froxlor#469] opened 2017-08-15 21:40 UTC
# Summary

The Froxlor.sql file contains an error. As an result of this the table mail_virtual is not createt
The MySQL error is  : ERROR 1101 (42000): BLOB/TEXT column 'destination' can't have a default value

DROP TABLE IF EXISTS `mail_virtual`;
CREATE TABLE `mail_virtual` (
  `id` int(11) NOT NULL auto_increment,
  `email` varchar(255) NOT NULL default '',
  `email_full` varchar(255) NOT NULL default '',
  `destination` text NOT NULL default '',   <--
  `domainid` int(11) NOT NULL default '0',
  `customerid` int(11) NOT NULL default '0',
  `popaccountid` int(11) NOT NULL default '0',
  `iscatchall` tinyint(1) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `email` (`email`)
) ENGINE=MyISAM CHARSET=utf8 COLLATE=utf8_general_ci;

This can be fixed by removing the default value of the script

# System information
* Froxlor version: 0.9.38.7 (DB: 201612110)
* Web server: apache2/php7
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: CentOS 7

**Comment by d00p** [comment] 2017-08-16 04:52
Duplicate of #433

**Closed by d00p** 2017-08-16 04:52 UTC
