### ISSUE TITLE
IP and Ports: Error when entering a Private IP range

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#802] opened 2020-02-06 17:23 UTC
Hello,

when I try to change a setting regarding an existing IP in a private range (10.x.x.x) the webinterface gives me a "wrong IP" error.

As said the IP already was added earlier and I just wanted to change something (SSL path).

Regards,

Af0x

**Comment by d00p** [comment] 2020-02-06 17:39
Define "a" setting please, there are many

**Comment by Af0x** [comment] 2020-02-06 17:43
> I just wanted to change something (SSL path).

**Comment by d00p** [comment] 2020-02-06 17:55
Does it really hurt to name the settings section and group?

**Comment by Af0x** [comment] 2020-02-06 18:05
Resources -> IPs and Ports -> Edit existing Private IP with SSL -> Webserver SSL config -> change "Path to the SSL Certificate", "Path to the SSL Keyfile" and "Path to the SSL CertificateChainFile"

**Comment by d00p** [comment] 2020-02-06 18:22
Thank you

**Comment by d00p** [comment] 2020-02-06 18:55
So, first I wonder how you managed to enter a private ip address in IPs/Ports as this is not possible, not with `IpsAndPorts.add()` nor with `IpsAndPorts.update()`

**Comment by Af0x** [comment] 2020-02-07 11:12
Well, as far as I can remember it was possible in the past. Question is: why not? Would be nice if it was (again?).

**Comment by d00p** [comment] 2020-02-07 12:18
Possible that only reserved ranges were forbidden in times of 0.9.x but it was never intended that private ip ranges can be used as it possibly breaks functionality for different services, especially regarding DNS. I have yet not seen any set up where this would be required. You will always need at least one public ip address to communicate with the internet somewhere in your setup and if you want a domain to be reachable online it needs at least one public ip address A record etc.etc.etc. So even with some setups behind whatsoever-service - at the end, you need one public address and that's the one froxlor needs too

**Comment by Af0x** [comment] 2020-02-07 12:30
Yeah ok but why shouldn´t it also be possible to access Froxlor from a private IP address? I mean the named setting influences the apache/nginx config for the whole server so if this is not possible you can´t put a rule for this private address spaces and thus can´t reach it from there and always have to go the public way.

**Comment by d00p** [comment] 2020-02-07 12:35
> Yeah ok but why shouldn´t it also be possible to access Froxlor from a private IP address?

because 99% of the use-case does not require that. If you want a completely private setup, only for your LAN or whatever then yes, that would require to be able to use private address ranges but for a hosting panel this is quite unusual and makes no sense in 98% of the cases. 

So, to cut this short:

1) no this is not a bug, it works as inteded
2) feel free to discuss possible changes for that behaviour for different setups on the forum

**Comment by Af0x** [comment] 2020-02-07 12:40
Still think it wouldn´t hurt if this restriction would be removed. It´s just an option and nobody forces an admin to chose this private space. But to forbid it is just not necessary.

**Comment by d00p** [comment] 2020-02-07 12:44
Feel free to patch froxlor as you require...it's open source after all

**Comment by Af0x** [comment] 2020-02-07 13:07
Can you give me a hint on what file(s) I have to look at?

**Comment by d00p** [comment] 2020-02-07 13:23
IpsAndPorts.add() : https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/IpsAndPorts.php#L173

IpsAndPorts.update() : 
https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Api/Commands/IpsAndPorts.php#L370

Adjust 5th parameter of `\Froxlor\Validate\Validate::validate_ip2()` to `true` to allow private ranges

**Comment by Af0x** [comment] 2020-02-07 13:36
Thank you.

If I had the skills I´d make a pull request for an option to set this parameter.

**Comment by nyov** [comment] 2020-03-01 09:03
I've been using Froxlor in containers with private IPs for years. The webserver(s) run behind a reverse proxy, and the firewall handles public IPs.
I don't understand why this wouldn't be an acceptable config for froxlor anymore, but thanks for the code hints from me as well!

**Comment by patschi** [comment] 2020-03-01 18:01
In case it's relevant: I'm also using a private IP address for certain sites.
1) To make them only listen in the internal network (I have sites connected to each other via VPN)
2) I "abuse" Froxlor for managing SSL certificates for a few custom nginx vhosts. When no IPs are assigned to a domain, no certificates are renewed. That's why I assign a private IPv6 address so that ACME client is triggered for them as well.

**Closed** 2020-03-02 08:51 UTC
